#! /bin/bash
curl --header "Content-Type: application/json" --cookie cookies.txt --data '{"_id": null, "name": "Carl", "vorname": "Coyote", "geschlecht": "m", "version": null}' "http://localhost:8080/schueler"
